### PR TITLE
Session I'd 

### PR DESCRIPTION
**Pull request by Teamolduser**

### CODE REVIEW

**Comment by Guru322** [comment]
wtf is this shit

**Comment by Teamolduser** [comment]
> wtf is this shit

Isko session ka banwana rha so bana diya mene

**Comment by Guru322** [comment]
> > wtf is this shit
> 
> Isko session ka banwana rha so bana diya mene

Ara bhay but ye to esm code hai
But aapne commonjs ke require kyu use kiye ho aur
fs ke imports to already defined hai

**Comment by Guru322** [comment]
Like `import axios from 'axios' `

**Pull request merged**
